server:
  port: 8081

spring:
  datasource:
    username: username
    password: password
    url: jdbc:mysql://localhost:3306/mydb?allowPublicKeyRetrieval=true&useSSL=false
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
#    show-sql: true
    defer-datasource-initialization: true

#logging:
#  level:
#    root: debug
